services:
    nfq_weather.parser.OpenWeatherMap:
        class: Nfq\WeatherBundle\Parsers\OpenWeatherMapParser
        public: false

    nfq_weather.provider.OpenWeatherMap:
        class: Nfq\WeatherBundle\Providers\OpenWeatherMapProvider
        arguments: ["@nfq_weather.parser.OpenWeatherMap", "%api-weather%"]

    nfq_weather.parser.Yahoo:
        class: Nfq\WeatherBundle\Parsers\YahooParser
        public: false

    nfq_weather.provider.Yahoo:
        class: Nfq\WeatherBundle\Providers\YahooProvider
        arguments: ["@nfq_weather.parser.Yahoo"]

    nfq_weather.provider.Delegating:
        class: Nfq\WeatherBundle\Providers\DelegatingProvider
        arguments: ["%nfq_weather.delegating_providers%", "%api_key%"]

    nfq_weather.provider.cached:
        class: Nfq\WeatherBundle\Providers\CachedProvider
        arguments: ["%nfq_weather.cached_provider%", "%nfq_weather.cached_providers%", "%ttl%", "%api_key%"]